# Generated by Django 4.0.2 on 2022-02-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_client_qarz_alter_mahsulot_brend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ism',
        ),
    ]
